/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PaymentSuccessImport } from './routes/payment-success'

// Create Virtual Routes

const PaymentLazyImport = createFileRoute('/payment')()
const CheckoutBiodataLazyImport = createFileRoute('/checkout-biodata')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PaymentLazyRoute = PaymentLazyImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/payment.lazy').then((d) => d.Route))

const CheckoutBiodataLazyRoute = CheckoutBiodataLazyImport.update({
  id: '/checkout-biodata',
  path: '/checkout-biodata',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/checkout-biodata.lazy').then((d) => d.Route),
)

const PaymentSuccessRoute = PaymentSuccessImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessImport
      parentRoute: typeof rootRoute
    }
    '/checkout-biodata': {
      id: '/checkout-biodata'
      path: '/checkout-biodata'
      fullPath: '/checkout-biodata'
      preLoaderRoute: typeof CheckoutBiodataLazyImport
      parentRoute: typeof rootRoute
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/checkout-biodata': typeof CheckoutBiodataLazyRoute
  '/payment': typeof PaymentLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/checkout-biodata': typeof CheckoutBiodataLazyRoute
  '/payment': typeof PaymentLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/checkout-biodata': typeof CheckoutBiodataLazyRoute
  '/payment': typeof PaymentLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/payment-success' | '/checkout-biodata' | '/payment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payment-success' | '/checkout-biodata' | '/payment'
  id: '__root__' | '/' | '/payment-success' | '/checkout-biodata' | '/payment'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  CheckoutBiodataLazyRoute: typeof CheckoutBiodataLazyRoute
  PaymentLazyRoute: typeof PaymentLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  CheckoutBiodataLazyRoute: CheckoutBiodataLazyRoute,
  PaymentLazyRoute: PaymentLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/payment-success",
        "/checkout-biodata",
        "/payment"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/payment-success": {
      "filePath": "payment-success.jsx"
    },
    "/checkout-biodata": {
      "filePath": "checkout-biodata.lazy.jsx"
    },
    "/payment": {
      "filePath": "payment.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
