/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const OrderHistoryLazyImport = createFileRoute('/orderHistory')()
const NotificationsLazyImport = createFileRoute('/notifications')()
const AkunLazyImport = createFileRoute('/akun')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const OrderHistoryLazyRoute = OrderHistoryLazyImport.update({
  id: '/orderHistory',
  path: '/orderHistory',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orderHistory.lazy').then((d) => d.Route))

const NotificationsLazyRoute = NotificationsLazyImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/notifications.lazy').then((d) => d.Route))

const AkunLazyRoute = AkunLazyImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/akun.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunLazyImport
      parentRoute: typeof rootRoute
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/orderHistory': {
      id: '/orderHistory'
      path: '/orderHistory'
      fullPath: '/orderHistory'
      preLoaderRoute: typeof OrderHistoryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/akun': typeof AkunLazyRoute
  '/notifications': typeof NotificationsLazyRoute
  '/orderHistory': typeof OrderHistoryLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/akun': typeof AkunLazyRoute
  '/notifications': typeof NotificationsLazyRoute
  '/orderHistory': typeof OrderHistoryLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/akun': typeof AkunLazyRoute
  '/notifications': typeof NotificationsLazyRoute
  '/orderHistory': typeof OrderHistoryLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/akun' | '/notifications' | '/orderHistory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/akun' | '/notifications' | '/orderHistory'
  id: '__root__' | '/' | '/akun' | '/notifications' | '/orderHistory'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AkunLazyRoute: typeof AkunLazyRoute
  NotificationsLazyRoute: typeof NotificationsLazyRoute
  OrderHistoryLazyRoute: typeof OrderHistoryLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AkunLazyRoute: AkunLazyRoute,
  NotificationsLazyRoute: NotificationsLazyRoute,
  OrderHistoryLazyRoute: OrderHistoryLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/akun",
        "/notifications",
        "/orderHistory"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/akun": {
      "filePath": "akun.lazy.jsx"
    },
    "/notifications": {
      "filePath": "notifications.lazy.jsx"
    },
    "/orderHistory": {
      "filePath": "orderHistory.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
